apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:

  - name: nginx
    image: nginx:1.21.6
    ports:
    - containerPort: 80
      name: http
      protocol: TCP

    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: ubuntu-volume
  volumes:
  - name: ubuntu-volume
    persistentVolumeClaim:
      claimName: ubuntu-pvc
