apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:20.04
    ports:
    - containerPort: 80
      name: http
      protocol: TCP        
    args:
    - "./scripts/script.sh"

    volumeMounts:
    - name: cache-volume
      mountPath: /usr/share/nginx/html
    - name: wrapper1
      mountPath: /scripts


  - name: nginx
    image: nginx:1.21.6-alpine
    ports:
    - containerPort: 80
      name: http
      protocol: TCP

    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: cache-volume
  volumes:
  - name: cache-volume
  - name: wrapper1
    configMap:
      name: wrapper1
      defaultMode: 0777

    # emptyDir: {}
