apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:20.04
    ports:
    - containerPort: 80
      name: http
      protocol: TCP        
    args:
    - "./scripts/script.sh"

    volumeMounts:
    - name: wrapper1
      mountPath: /scripts
    - mountPath: /usr/share/nginx/html
      name: ubuntu-volume
  volumes:
  - name: ubuntu-volume
    persistentVolumeClaim:
      claimName: ubuntu-pvc
  - name: wrapper1
    configMap:
      name: wrapper1
      defaultMode: 0777

