apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-pvc1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: nginxapp
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: nginxapp


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-volume
data:
  script.sh: |
    #!/bin/bash
    rm -rf /usr/share/nginx/html

    apt-get update
    apt-get install git -y
    apt-get install curl -y
    cd ../
    git clone --recurse-submodules https://github.com/chazapis/hy548.git
    curl -L https://github.com/gohugoio/hugo/releases/download/v0.96.0/hugo_extended_0.96.0_Linux-64bit.deb -o hugo.deb
    apt install ./hugo.deb
    hugo version 
    cd  hy548
    cd html
    hugo -D
    cp -r public/. /scripts1/

  check.sh: |
    #!/bin/bash

    echo "hey"   

    sleep 120

    diff -q /scripts1/  /usr/share/nginx/html/ 1>/dev/null
    if [[ $? == "0" ]]
    then
      echo "The same"
    else
      echo "Not the same"
      cp -r /scripts1/. /usr/share/nginx/html/
    fi
    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6
  
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: ubuntu-volume

      initContainers:
      - name: ubuntu
        image: ubuntu:20.04     
        args:
        - "./scripts/check.sh"

        volumeMounts:
        - name: ubuntu-volume
          mountPath: /usr/share/nginx/html

        
        - name: script-volume
          mountPath: /scripts
          
        - name: ubuntu-volume1
          mountPath: /scripts1


      volumes:
      - name: ubuntu-volume
        persistentVolumeClaim:
          claimName: ubuntu-pvc

      - name: ubuntu-volume1
        persistentVolumeClaim:
          claimName: ubuntu-pvc1

      - name: script-volume
        configMap:
          name: script-volume
          defaultMode: 0777

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-repeating
spec:
  schedule: "15 2 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: ubuntu
            image: ubuntu:20.04     
            args:
            - "./scripts/script.sh"

            volumeMounts:
            - name: script-volume
              mountPath: /scripts
            
            - name: ubuntu-volume1
              mountPath: /scripts1

          volumes:

          - name: ubuntu-volume1
            persistentVolumeClaim:
              claimName: ubuntu-pvc1

          - name: script-volume
            configMap:
              name: script-volume
              defaultMode: 0777