apiVersion: batch/v1
kind: Job
metadata:
  name: john1
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: ubuntu
        image: ubuntu:20.04
        
        
        
        args:
        - "./scripts/wrapper.sh"


        volumeMounts:
        - name: wrapper
          mountPath: /scripts

      volumes:
      - name: wrapper
        configMap:
          name: wrapper
          defaultMode: 0777
