name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image 
    build:
      name: Build Docker image and push to repositories
      # run only when code is compiling and tests are passing
      runs-on: nginx:1.21.6

      # steps to perform in job
      steps:


        - name: Checkout code
          uses: actions/checkout@v2



        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}



        - name: Build image and push to Docker Hub and GitHub Container Registry
          run: |
            docker build -t "hy548:csdp1235" .
