name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
      name: Buildand push to  Docker image 
      runs-on: nginx:1.21.6

      steps:

        - name: Checkout code
          uses: actions/checkout@v2


        # setup Docker buld action
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1


        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            
        - name: Build and Push
          uses: docker/build-push-action@v2
          with:
           
            context: ./Homework1
            # Note: tags has to be all lower-case
            tags: |
              johnarakas/hy548:latest 
            # build on feature branches, push only on main branch
            push: ${{ github.ref == 'refs/heads/main' }}

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}


